#!/usr/bin/env node
// Read-only lexical dedupe audit for blog-src/src/content/posts.
//
// Reports the closest title pairs by the SAME Jaccard-similarity algorithm
// the AI draft pipeline uses as its lexical fallback (scripts/lib/blog-post.js
// -> tokenize()/jaccard(), exposed here via the exported `findMostSimilar`).
// This script imports that module directly rather than reimplementing the
// tokenizer, so it can never silently drift from the real dedupe behavior.
//
// It does NOT call any network or embedding API, and does not write anything
// — it only reads blog-src/src/content/posts/*.md and prints a report.
//
// Usage:
//   node .claude/skills/resumesite-diagnostics-and-tooling/scripts/dedupe-audit.mjs [topN]
//
// topN (optional, default 15): how many of the closest pairs to print.

import {
  getExistingPosts,
  findMostSimilar,
  DUPLICATE_THRESHOLD,
} from '../../../../scripts/lib/blog-post.js';

// getExistingPosts() resolves POSTS_DIR internally (relative to blog-post.js),
// so this script needs no path handling of its own.
const topN = Number(process.argv[2]) || 15;

const posts = getExistingPosts();
if (posts.length < 2) {
  console.log(`Only ${posts.length} post(s) found — nothing to compare.`);
  process.exit(0);
}

// All-pairs Jaccard, computed via the pipeline's own findMostSimilar() so the
// score for every pair is generated by the exact same tokenize()/jaccard()
// implementation the real dedupe guard uses — not a reimplementation.
const pairs = [];
for (let i = 0; i < posts.length; i++) {
  for (let j = i + 1; j < posts.length; j++) {
    const { score } = findMostSimilar(posts[i].title, [posts[j].title]);
    pairs.push({ a: posts[i], b: posts[j], score });
  }
}

pairs.sort((x, y) => y.score - x.score);

console.log(`Scanned ${posts.length} posts (${pairs.length} pairs).`);
console.log(
  `Lexical DUPLICATE_THRESHOLD (scripts/lib/blog-post.js) = ${DUPLICATE_THRESHOLD}` +
    ' — the pipeline only falls back to this when semantic embedding is unavailable.\n',
);

console.log(`Top ${Math.min(topN, pairs.length)} closest title pairs by Jaccard similarity:\n`);
for (const { a, b, score } of pairs.slice(0, topN)) {
  const flag = score >= DUPLICATE_THRESHOLD ? '  <-- AT/ABOVE lexical duplicate threshold' : '';
  console.log(`${(score * 100).toFixed(1)}%  "${a.title}"  <->  "${b.title}"${flag}`);
}

const atOrAbove = pairs.filter((p) => p.score >= DUPLICATE_THRESHOLD);
console.log(
  `\n${atOrAbove.length} pair(s) at/above the lexical duplicate threshold (${DUPLICATE_THRESHOLD}).`,
);
if (atOrAbove.length > 0) {
  console.log(
    'Note: the live pipeline dedupes primarily via SEMANTIC embedding similarity ' +
      '(default threshold 0.85, see resumesite-config-and-flags); Jaccard is only the ' +
      'fallback when no embed adapter is configured or embedding fails. A lexical hit ' +
      'here does not by itself mean the real pipeline would have rejected the post.',
  );
}
