CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  ip TEXT,
  ts INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_submissions_ts ON submissions (ts DESC);
